services:
  easyserver:
    image: easyserver
    build:
      context: .
      dockerfile: src/EasyServer/Dockerfile
    container_name: easyserver
    ports:
      - "11000:11000"
    volumes:
      - easyserver_logs:/app/logs

volumes:
  easyserver_logs:
